language: node_js
node_js: ['8']
sudo: false

before_deploy:
  - mkdir _site
  - node index.js > _site/package_macchina_index.json

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: gh-pages
  local_dir: _site
